language: php

php: 
  - 7.4.3

before_install:
  - travis_retry composer self-update
  - travis_retry composer validate --no-check-publish

install:	
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit	

notifications:
  webhooks:
    urls:
    - $MYWEBHOOK/travis-ci.php
  on_success: always
  on_failure: always
  on_start: never
  on_cancel: never
  on_error: always
