language: php

os: linux

dist: xenial

php: 
  - 7.4.3

before_install:
  - travis_retry composer self-update
  - travis_retry composer validate --no-check-publish

install:	
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit	

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $MYWEBHOOK
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $MYWEBHOOK
notifications:
  email:
    recipients:
      - $MYEMAILADDRESS
    on_success: always # moet eigenlijk op never staan
    on_failure: always
